version: "3.8"
services:
  postgres.railway.internal:
    image: postgres:15
    env_file:
      - ./produkk-api/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  produkk-api.railway.internal:
    build:
      context: ./produkk-api
    env_file:
      - ./produkk-api/.env
    ports:
      - "3009:3009"
    depends_on:
      - postgres.railway.internal
    restart: unless-stopped

  produkk-ui.railway.internal:
    build:
      context: ./produkk-ui
      dockerfile: Dockerfile
    ports:
    - "4209:80"
    depends_on:
      - produkk-api.railway.internal
    restart: unless-stopped

  redis.railway.internal:
    image: redis:7-alpine
    env_file:
      - ./produkk-api/.env
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: > 
      sh -c "echo \"user default on >$${REDIS_PASSWORD} ~* +@all\" > /data/users.acl && redis-server --aclfile /data/users.acl"
    ports:
      - "6379:6379"

volumes:
  db-data:
  redis-data: