version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: vexay
      POSTGRES_PASSWORD: vexaypassw
      POSTGRES_DB: produkk
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./produkk-api
    environment:
      DATABASE_URL: postgresql://vexay:vexaypassw@db:5432/produkk
      NODE_ENV: production
      JWT_SECRET: 288f35c7c8626da74e7f763171b28ea7
      JWT_EXPIRES_IN: 7d
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: unless-stopped

  ui:
    build:
      context: ./produkk-ui
    ports:
      - "4200:4200"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db-data:
