server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/ { proxy_pass http://api:3009/auth/; proxy_set_header Host $host; }
  location /tasks { proxy_pass http://api:3009/tasks; proxy_set_header Host $host; }
  location /tasks/ { proxy_pass http://api:3009/tasks/; proxy_set_header Host $host; }
}